# Esercizio 1

Definire i  numpy array a=[1.2, 5.4, 6, 1.59] e b=[5.2, 1.2, 1.5, 2] ed eseguire le seguenti operazioni:
  - calcolare la radice quadrata degli elementi di a;
   - calcolare 𝑒xp(𝑎/2) ;
   - calcolare il vettore somma tra a e b ;
   - moltiplicare ogni elemento di a per il corrispondente elemento di b;
   - creare un vettore di valori uniformemente equispaziati tra 0 e 30 con passo  0.5;
   - creare un vettore di 100 valori uniformemente equispaziati tra 1 e 2.
   - usare linspace() per creare un numpy array 2x6 con prima riga di 6 valori uniformi compresi tra 10 e 20 e seconda riga 6 valori     
      uniformi compresi tra  20 e 10;
   - calcolare il prodotto scalare tra a e b;
   - creare la matrice A che ha come righe i vettori a e b ;
   - calcolare il prodotto scalare tra i due vettori a e b;
   - eseguire il prodotto della matrice A per il vettore b e assegnarlo ad y;
   - costruire una matrice diagonale D a partire dal vettore a;

In [15]:
import numpy as np
import math

a=np.array([1.2, 5.4, 6, 1.59])
b=np.array([5.2, 1.2, 1.5, 2 ])



a1 = np.sqrt(a)

a2= np.exp(a/2)

c= a + b

ab = a*b

z = np.arange(0,30.5,0.5)

t = np.linspace(1,2,100)
print(t)
C= np.array([np.linspace(10,20,6),np.linspace(20,10,6)])
print(C)
ps= np.dot(a,b)
print("ps=",ps)

a1=a[np.newaxis,:]
b1=b[np.newaxis,:]
A=np.concatenate((a1,b1))
print("A=",A)


y = np.dot(A,b)

D=np.diag(a)
print("D=",D)

[1.         1.01010101 1.02020202 1.03030303 1.04040404 1.05050505
 1.06060606 1.07070707 1.08080808 1.09090909 1.1010101  1.11111111
 1.12121212 1.13131313 1.14141414 1.15151515 1.16161616 1.17171717
 1.18181818 1.19191919 1.2020202  1.21212121 1.22222222 1.23232323
 1.24242424 1.25252525 1.26262626 1.27272727 1.28282828 1.29292929
 1.3030303  1.31313131 1.32323232 1.33333333 1.34343434 1.35353535
 1.36363636 1.37373737 1.38383838 1.39393939 1.4040404  1.41414141
 1.42424242 1.43434343 1.44444444 1.45454545 1.46464646 1.47474747
 1.48484848 1.49494949 1.50505051 1.51515152 1.52525253 1.53535354
 1.54545455 1.55555556 1.56565657 1.57575758 1.58585859 1.5959596
 1.60606061 1.61616162 1.62626263 1.63636364 1.64646465 1.65656566
 1.66666667 1.67676768 1.68686869 1.6969697  1.70707071 1.71717172
 1.72727273 1.73737374 1.74747475 1.75757576 1.76767677 1.77777778
 1.78787879 1.7979798  1.80808081 1.81818182 1.82828283 1.83838384
 1.84848485 1.85858586 1.86868687 1.87878788 1.88888889 1.89898

# Esercizio 2

Costruire  i seguenti Numpy array 2d utilizzando il minor numero di istruzioni possibili

<img src="ese2.png" width="500">

In [16]:
import numpy as np

A = np.full((3,3),2)
A= np.concatenate((A,np.full((3,1),3)),1)

print("A \n",A)
B=2*np.eye(3)
B=np.concatenate((B,[np.linspace(1,10,10), np.linspace(1,10,10), np.linspace(1,10,10)]),1)
print("B \n",B)
a=np.array([2,2,2,2,2])
b= np.array([-1,-1,-1,-1])
C= np.diag(a)+np.diag(b,-1)+np.diag(b,1)
print("C \n ",C)
D=np.zeros((6,4))
D[4:6,2:4]=5*np.eye(2)
D[0:2,0:2]=np.full((2,2),2)
D[0:2,2:4]=np.full((2,2),3)
print("D \n",D)

A 
 [[2 2 2 3]
 [2 2 2 3]
 [2 2 2 3]]
B 
 [[ 2.  0.  0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [ 0.  2.  0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [ 0.  0.  2.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]]
C 
  [[ 2 -1  0  0  0]
 [-1  2 -1  0  0]
 [ 0 -1  2 -1  0]
 [ 0  0 -1  2 -1]
 [ 0  0  0 -1  2]]
D 
 [[2. 2. 3. 3.]
 [2. 2. 3. 3.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 5. 0.]
 [0. 0. 0. 5.]]


# Esercizio 3

Calcolare la somma dei primi n numeri naturali dispari sia utilizzando un ciclo for che servendosi dell'istruzione sum di numpy.

In [17]:
n=int(input('Numero di dati'))

somma=0
for i in range(1,n+1,2):
    somma=somma+i
       
print("Somma ", somma)

a1= np.array(list(range(1,n+1,2)))
somma1= np.sum(a1)

print("Somma1= ", somma1)

Somma  144
Somma1=  144


# Esercizo 4

Scrivere una function Python per generare l'n-esimo termine (n > 2) della successione
di Fibonacci. Scrivere poi una function ricorsiva che risolva lo stesso problema
e confrontare i tempi di calcolo delle due functions per n = 24.

In [18]:
import time


def fibonacci(n):
#FIBONACCI  Fibonacci sequence
#   f = FIBONACCI(n) generates the first n Fibonacci numbers.

     f = np.zeros((n,))
     f[0] = 1
     f[1] = 1
     for k in range(2,n):
         f[k] = f[k-1] + f[k-2]
     fn=f[-1]   
     return fn


def fib_ric(n):
   
    if n <= 2:   
        f = 1
        return f
    else:
       f = fib_ric(n-1) + fib_ric(n-2)
       return f


n=int(input('inserisci valore di n>=2: '))

start_time = time.perf_counter()
f1=fibonacci(n)
end_time =time.perf_counter()
print("Tempo Fibonacci Iterativo", end_time-start_time)

start_time = time.perf_counter()
f2=fib_ric(n)
end_time = time.perf_counter()
print("Tempo Fibonacci Ricorsivo", end_time-start_time)

Tempo Fibonacci Iterativo 6.900000153109431e-05
Tempo Fibonacci Ricorsivo 0.006876599974930286


In [19]:
print(f1)


46368.0


In [20]:
print(f2)

46368
